cellsociety_team13: HexagonalNeighbor Class Reference
HexagonalNeighbor Class Reference
Public Member Functions
HexagonalNeighbor (Boundary bounds)
List< Integer[]> getNeighbors (Cell[][] grid, int r, int c, int scalar)
Public Member Functions inherited from HalfNeighbor
HalfNeighbor (Boundary bounds)
List< Integer[]> getNeighbors (Cell[][] grid, int r, int c, int scalar)
Public Member Functions inherited from Neighbor
abstract List< Integer[]> getNeighbors (Cell[][] grid, int row, int col, int scalar)
List< Integer[]> getNeighbors (Cell[][] grid, int row, int col)
Private Member Functions
List< Integer[]> makeCorners (Cell[][] grid, int r, int c, int d, int scalar)
Additional Inherited Members
Protected Attributes inherited from HalfNeighbor
Boundary myBounds
Detailed Description
Definition at line 9 of file HexagonalNeighbor.java.
Constructor & Destructor Documentation
HexagonalNeighbor.HexagonalNeighbor (Boundary bounds)
Definition at line 13 of file HexagonalNeighbor.java.
Member Function Documentation
List<Integer[]> HexagonalNeighbor.getNeighbors (Cell grid[][], int r, int c, int scalar)
Definition at line 19 of file HexagonalNeighbor.java.
References makeCorners().
List<Integer[]> HexagonalNeighbor.makeCorners (Cell grid[][], int r, int c, int d, int scalar) private
Definition at line 31 of file HexagonalNeighbor.java.
References Boundary.findCell(), and HalfNeighbor.myBounds.
Referenced by getNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/HexagonalNeighbor.java