cellsociety_team13: WatorController Class Reference
WatorController Class Reference
Public Member Functions
WatorController (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Public Member Functions inherited from ComplexController
ComplexController (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Public Member Functions inherited from Controller
abstract Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Controller (Map< String, String >parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Member Functions
void cellUpdate (GridData data) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
List< String > typeTriage (List< String > list)
Protected Member Functions inherited from ComplexController
abstract void cellUpdate (GridData data) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
abstract List< String > typeTriage (List< String > list)
Protected Member Functions inherited from Controller
boolean contains (List< Integer[]> updatedCoordinates, Integer[] curCoordinates)
Private Member Functions
void manipulateCell (GridData data)
List< Integer[]> makeEligible (GridData data, String type)
List< Integer[]> getNeighbors (GridData data, String s)
Integer[] getDestination (List< Integer[]> eligibleDestinations)
boolean deadShark (Cell cell)
Additional Inherited Members
Static Public Attributes inherited from Controller
static final int X_COORD = 0
static final int Y_COORD = 1
Static Protected Member Functions inherited from Controller
static Cell makeCell (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Attributes inherited from Controller
Boundary myBoundary
Neighbor myNeighbor
Detailed Description
Definition at line 7 of file WatorController.java.
Constructor & Destructor Documentation
WatorController.WatorController (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Definition at line 9 of file WatorController.java.
Member Function Documentation
void WatorController.cellUpdate (GridData data) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException protected
Definition at line 122 of file WatorController.java.
References deadShark(), Controller.makeCell(), and manipulateCell().
boolean WatorController.deadShark (Cell cell) private
Definition at line 114 of file WatorController.java.
Referenced by cellUpdate().
Integer [] WatorController.getDestination (List< Integer[]> eligibleDestinations) private
Definition at line 110 of file WatorController.java.
Referenced by manipulateCell().
List<Integer[]> WatorController.getNeighbors (GridData data, String s) private
Definition at line 85 of file WatorController.java.
References Controller.contains(), GridData.getCol(), GridData.getGrid(), GridData.getList(), Neighbor.getNeighbors(), GridData.getRow(), Controller.myNeighbor, and Cell.toString().
Referenced by makeEligible().
List<Integer[]> WatorController.makeEligible (GridData data, String type) private
Definition at line 71 of file WatorController.java.
References getNeighbors().
Referenced by manipulateCell().
void WatorController.manipulateCell (GridData data) private
Definition at line 13 of file WatorController.java.
References GridData.curCell(), GridData.curCoord(), GridData.getCol(), getDestination(), GridData.getGrid(), GridData.getList(), GridData.getNewGrid(), GridData.getRow(), makeEligible(), and Cell.toString().
Referenced by cellUpdate().
List<String> WatorController.typeTriage (List< String > list) protected
Definition at line 136 of file WatorController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/WatorController.java