cellsociety_team13: SegregationController Class Reference
SegregationController Class Reference
Public Member Functions
SegregationController (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Public Member Functions inherited from SimpleController
SimpleController (Map< String, String >parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Public Member Functions inherited from Controller
abstract Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Controller (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Member Functions
String getNeighborsState (Cell[][] grid, List< Integer[]> neighbors)
Cell newState (Cell[][] newGrid, Cell cell, String neighborsState, int r, int c) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Member Functions inherited from SimpleController
abstract String getNeighborsState (Cell[][] grid, List< Integer[]> neighbors)
abstract Cell newState (Cell[][] newGrid, Cell cell, String neighborsState, int r, int c) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Member Functions inherited from Controller
boolean contains (List< Integer[]> updatedCoordinates, Integer[] curCoordinates)
Private Member Functions
void makeEmptyList (Cell[][] grid)
String selectNeighborsState (double bC, double rC)
Private Attributes
double myHappyFraction
ArrayList< Integer[]> myEmptyList
ArrayList< Integer[]> updatedList
Additional Inherited Members
Static Public Attributes inherited from Controller
static final int X_COORD = 0
static final int Y_COORD = 1
Static Protected Member Functions inherited from Controller
static Cell makeCell (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Attributes inherited from Controller
Boundary myBoundary
Neighbor myNeighbor
Detailed Description
Definition at line 8 of file SegregationController.java.
Constructor & Destructor Documentation
SegregationController.SegregationController (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Definition at line 13 of file SegregationController.java.
Member Function Documentation
String SegregationController.getNeighborsState (Cell grid[][], List< Integer[]> neighbors) protected
Definition at line 41 of file SegregationController.java.
References selectNeighborsState(), Cell.toString(), Controller.X_COORD, and Controller.Y_COORD.
void SegregationController.makeEmptyList (Cell grid[][]) private
Definition at line 27 of file SegregationController.java.
References Cell.toString().
Referenced by runOneSim().
Cell SegregationController.newState (Cell newGrid[][], Cell cell, String neighborsState, int r, int c) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException protected
Definition at line 75 of file SegregationController.java.
References Controller.contains(), and Controller.makeCell().
Cell [][] SegregationController.runOneSim (Cell grid[][]) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Definition at line 21 of file SegregationController.java.
References makeEmptyList().
String SegregationController.selectNeighborsState (double bC, double rC) private
Definition at line 55 of file SegregationController.java.
References myHappyFraction.
Referenced by getNeighborsState().
Member Data Documentation
ArrayList<Integer[]> SegregationController.myEmptyList private
Definition at line 10 of file SegregationController.java.
double SegregationController.myHappyFraction private
Definition at line 9 of file SegregationController.java.
Referenced by selectNeighborsState().
ArrayList<Integer[]> SegregationController.updatedList private
Definition at line 11 of file SegregationController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/SegregationController.java