cellsociety_team13: SquareGrid Class Reference
SquareGrid Class Reference
Public Member Functions
SquareGrid (double gridSize, Cell[][] cells)
Group getGroup ()
void update (Cell[][] cells)
Public Member Functions inherited from Grid
abstract void update (Cell[][] cells)
Private Member Functions
void populateGrid (Cell[][] cells)
void setBack (Shape s, Cell c)
void setRed (Shape s)
Private Attributes
Group myGrid
Shape[][] myShapes
double mySpacing
Detailed Description
Definition at line 6 of file SquareGrid.java.
Constructor & Destructor Documentation
SquareGrid.SquareGrid (double gridSize, Cell cells[][])
Definition at line 12 of file SquareGrid.java.
References populateGrid().
Member Function Documentation
Group SquareGrid.getGroup ()
Definition at line 46 of file SquareGrid.java.
References myGrid.
void SquareGrid.populateGrid (Cell cells[][]) private
Definition at line 21 of file SquareGrid.java.
References setBack(), and setRed().
Referenced by SquareGrid().
void SquareGrid.setBack (Shape s, Cell c) private
Definition at line 37 of file SquareGrid.java.
References Cell.getColor().
Referenced by populateGrid().
void SquareGrid.setRed (Shape s) private
Definition at line 42 of file SquareGrid.java.
Referenced by populateGrid().
void SquareGrid.update (Cell cells[][])
Definition at line 50 of file SquareGrid.java.
Member Data Documentation
Group SquareGrid.myGrid private
Definition at line 8 of file SquareGrid.java.
Referenced by getGroup().
Shape [][] SquareGrid.myShapes private
Definition at line 9 of file SquareGrid.java.
double SquareGrid.mySpacing private
Definition at line 10 of file SquareGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/SquareGrid.java