cellsociety_team13: Cell Class Reference
Cell Class Reference
Public Member Functions
Cell (String name)
Cell (Map< String, String > params)
Shape getShape ()
Color getColor ()
String toString ()
void setColor (Color color)
Static Public Member Functions
static void setCellSize (double width, double height)
Protected Member Functions
double getWidth ()
double getHeight ()
Private Attributes
Shape myShape
String myName
Color myColor
Static Private Attributes
static double myWidth
static double myHeight
Detailed Description
Definition at line 12 of file Cell.java.
Constructor & Destructor Documentation
Cell.Cell (String name)
Definition at line 24 of file Cell.java.
Referenced by FishCell.reproducingResult(), and SharkCell.reproducingResult().
Cell.Cell (Map< String, String > params)
Definition at line 30 of file Cell.java.
Member Function Documentation
Color Cell.getColor ()
Definition at line 50 of file Cell.java.
References myColor.
Referenced by TriangleGrid.setBack().
double Cell.getHeight () protected
Definition at line 46 of file Cell.java.
References myHeight.
Shape Cell.getShape ()
Definition at line 38 of file Cell.java.
References myShape.
Referenced by FishCell.FishCell(), and SharkCell.SharkCell().
double Cell.getWidth () protected
Definition at line 42 of file Cell.java.
References myWidth.
static void Cell.setCellSize (double width, double height) static
Definition at line 62 of file Cell.java.
Referenced by CellSociety.readNewXML().
void Cell.setColor (Color color)
Definition at line 58 of file Cell.java.
String Cell.toString ()
Definition at line 54 of file Cell.java.
References myName.
Referenced by ComplexController.coordinatesTriage(), WatorController.getNeighbors(), FireController.getNeighborsState(), LifeController.getNeighborsState(), SegregationController.getNeighborsState(), SegregationController.makeEmptyList(), WatorController.manipulateCell(), CellSocietyView.updateChartLines(), and CellSociety.updateColors().
Member Data Documentation
Color Cell.myColor private
Definition at line 21 of file Cell.java.
Referenced by getColor().
double Cell.myHeight static private
Definition at line 15 of file Cell.java.
Referenced by getHeight().
String Cell.myName private
Definition at line 19 of file Cell.java.
Referenced by toString().
Shape Cell.myShape private
Definition at line 17 of file Cell.java.
Referenced by getShape().
double Cell.myWidth static private
Definition at line 14 of file Cell.java.
Referenced by getWidth().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/Cell.java