cellsociety_team13: FishCell Class Reference
FishCell Class Reference
Public Member Functions
FishCell ()
FishCell (Map< String, String > params)
int getAge ()
Cell reproducingResult ()
Cell ageOneChronon ()
String toString ()
Public Member Functions inherited from Cell
Cell ()
Shape getShape ()
Private Attributes
int myCurrAge
Static Private Attributes
static int myReproducingAge
static Color myColor
Additional Inherited Members
Static Public Member Functions inherited from Cell
static void setCellSize (double width, double height)
Protected Member Functions inherited from Cell
double getWidth ()
double getHeight ()
Detailed Description
Definition at line 9 of file FishCell.java.
Constructor & Destructor Documentation
FishCell.FishCell ()
Definition at line 17 of file FishCell.java.
References Cell.getShape().
Referenced by reproducingResult().
FishCell.FishCell (Map< String, String > params)
Definition at line 26 of file FishCell.java.
References Cell.getShape().
Member Function Documentation
Cell FishCell.ageOneChronon ()
Implements ReproducingCell.
Definition at line 59 of file FishCell.java.
int FishCell.getAge ()
Definition at line 43 of file FishCell.java.
References myReproducingAge.
Cell FishCell.reproducingResult ()
Implements ReproducingCell.
Definition at line 49 of file FishCell.java.
References FishCell().
String FishCell.toString ()
Definition at line 64 of file FishCell.java.
Member Data Documentation
Color FishCell.myColor static private
Definition at line 15 of file FishCell.java.
int FishCell.myCurrAge private
Definition at line 14 of file FishCell.java.
int FishCell.myReproducingAge static private
Definition at line 13 of file FishCell.java.
Referenced by getAge().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/FishCell.java