cellsociety_team13: AgentCell Class Reference
AgentCell Class Reference
Public Member Functions
AgentCell (GroundCell groundCell)
void ageOneChronon (GridData data)
Public Member Functions inherited from Cell
Cell (String name)
Cell (Map< String, String > params)
Shape getShape ()
Color getColor ()
String toString ()
void setColor (Color color)
Private Member Functions
void cellSwap (GridData data, Integer[] newLocation)
void harvest (Cell cell)
void leaveCurrentPatch (GridData data, Integer[] newLocation)
boolean sameLocation (GridData data, Integer[] newLocation)
Integer[] chooseNewLocation (GridData data)
Integer[] closestEligibleNeighbor (GridData data, List< Integer[]> eligibleNeighbors)
List< Integer[]> findEligibleNeighbors (GridData data)
Private Attributes
GroundCell myGroundCell
int mySugar
int mySugarMetabolism
int myVision
Additional Inherited Members
Static Public Member Functions inherited from Cell
static void setCellSize (double width, double height)
Protected Member Functions inherited from Cell
double getWidth ()
double getHeight ()
Detailed Description
Definition at line 6 of file AgentCell.java.
Constructor & Destructor Documentation
AgentCell.AgentCell (GroundCell groundCell)
Definition at line 14 of file AgentCell.java.
Member Function Documentation
void AgentCell.ageOneChronon (GridData data)
Implements Updatable.
Definition at line 19 of file AgentCell.java.
References cellSwap(), and chooseNewLocation().
void AgentCell.cellSwap (GridData data, Integer[] newLocation) private
Definition at line 32 of file AgentCell.java.
References GroundCell.ageOneChronon(), GridData.getCol(), GridData.getNewGrid(), GridData.getRow(), harvest(), leaveCurrentPatch(), and sameLocation().
Referenced by ageOneChronon().
Integer [] AgentCell.chooseNewLocation (GridData data) private
Definition at line 77 of file AgentCell.java.
References closestEligibleNeighbor(), findEligibleNeighbors(), GridData.getCol(), GridData.getRow(), Controller.X_COORD, and Controller.Y_COORD.
Referenced by ageOneChronon().
Integer [] AgentCell.closestEligibleNeighbor (GridData data, List< Integer[]> eligibleNeighbors) private
Definition at line 88 of file AgentCell.java.
References Controller.X_COORD, and Controller.Y_COORD.
Referenced by chooseNewLocation().
List<Integer[]> AgentCell.findEligibleNeighbors (GridData data) private
Definition at line 102 of file AgentCell.java.
Referenced by chooseNewLocation().
void AgentCell.harvest (Cell cell) private
Definition at line 51 of file AgentCell.java.
References GroundCell.harvest(), myGroundCell, and GroundCell.update().
Referenced by cellSwap(), and leaveCurrentPatch().
void AgentCell.leaveCurrentPatch (GridData data, Integer[] newLocation) private
Definition at line 66 of file AgentCell.java.
References GridData.getGrid(), GridData.getNewGrid(), harvest(), Controller.X_COORD, and Controller.Y_COORD.
Referenced by cellSwap().
boolean AgentCell.sameLocation (GridData data, Integer[] newLocation) private
Definition at line 73 of file AgentCell.java.
References GridData.getCol(), GridData.getRow(), Controller.X_COORD, and Controller.Y_COORD.
Referenced by cellSwap().
Member Data Documentation
GroundCell AgentCell.myGroundCell private
Definition at line 8 of file AgentCell.java.
Referenced by harvest().
int AgentCell.mySugar private
Definition at line 9 of file AgentCell.java.
int AgentCell.mySugarMetabolism private
Definition at line 10 of file AgentCell.java.
int AgentCell.myVision private
Definition at line 11 of file AgentCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/AgentCell.java