cellsociety_team13: AbstractGrid Class Reference
AbstractGrid Class Reference abstract
Public Member Functions
AbstractGrid (double gridSize, Cell[][] cells)
Group getGrid ()
void update (Cell[][] cells)
Protected Member Functions
abstract Shape[][] populateGrid (double gridSize, Cell[][] cells)
Private Member Functions
void displayGrid (Shape[][] shapes)
Private Attributes
Group myGrid
Shape[][] myShapes
Detailed Description
Definition at line 4 of file AbstractGrid.java.
Constructor & Destructor Documentation
AbstractGrid.AbstractGrid (double gridSize, Cell cells[][])
Definition at line 9 of file AbstractGrid.java.
References displayGrid(), and populateGrid().
Member Function Documentation
void AbstractGrid.displayGrid (Shape shapes[][]) private
Definition at line 28 of file AbstractGrid.java.
Referenced by AbstractGrid(), and update().
Group AbstractGrid.getGrid ()
Definition at line 16 of file AbstractGrid.java.
References myGrid.
Referenced by CellSocietyView.setupInitialGrid().
abstract Shape [][] AbstractGrid.populateGrid (double gridSize, Cell cells[][]) abstract protected
Referenced by AbstractGrid().
void AbstractGrid.update (Cell cells[][])
Definition at line 20 of file AbstractGrid.java.
References displayGrid().
Referenced by CellSocietyView.updateSimGrid().
Member Data Documentation
Group AbstractGrid.myGrid private
Definition at line 6 of file AbstractGrid.java.
Referenced by getGrid().
Shape [][] AbstractGrid.myShapes private
Definition at line 7 of file AbstractGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/AbstractGrid.java