cellsociety_team13: CellSocietyView Class Reference
CellSocietyView Class Reference
Public Member Functions
CellSocietyView (Stage s) throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException
Button getPlayElement ()
Button getPauseElement ()
Button getStepElement ()
Button getXMLElement ()
Button getSpeedupElement ()
Button getSlowdownElement ()
void openDialogBox (String s)
void updateSimGrid (Cell[][] cellGrid)
void setErrorText ()
void setBlankGrid ()
void generateTitle (String s)
void displayFrameRate (int frameRate)
File displayXMLChooser ()
void setButtonsPause (boolean disable)
void updateChartLines (Cell[][] cells, int numFrames, String[] names)
void generateChartLines (String[] cellNames)
void setGridGap (int gridLineGap)
Static Public Attributes
static final String DEFAULT_RESOURCE_PACKAGE = ""
static final int GRID_SIZE = 400
Private Member Functions
XYChart< Number, Number > initializeChart ()
void configureUI ()
void setupGameScene ()
void initializeButtons ()
void disableInitialButtons ()
void generateGrid () throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException
HBox createTitle ()
HBox makeSimulationButtons ()
HBox makeFrameControlButtons ()
HBox makeSpeedDisplay ()
HBox createErrorLocation ()
Private Attributes
Stage myStage
Scene myScene
Button myPlayButton
Button myPauseButton
Button myStepButton
Button myXMLButton
Button mySpeedupButton
Button mySlowdownButton
TextField mySpeedTextField
Text myErrorMsg
HBox myTitleBox
GridPane myRoot
GridPane mySimGrid
ResourceBundle myResources
LineChart< Number, Number > myChart
List< Series< Number, Number > > mySeries
Static Private Attributes
static final Font ERROR_FONT = Font.font("Arial", FontWeight.NORMAL, 12)
static final Font TITLE_FONT = Font.font("Helvetica", FontWeight.NORMAL, 32)
Detailed Description
Definition at line 38 of file CellSocietyView.java.
Constructor & Destructor Documentation
CellSocietyView.CellSocietyView (Stage s) throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException
Definition at line 67 of file CellSocietyView.java.
References configureUI(), disableInitialButtons(), generateGrid(), initializeButtons(), setBlankGrid(), and setupGameScene().
Member Function Documentation
void CellSocietyView.configureUI () private
Definition at line 236 of file CellSocietyView.java.
References createErrorLocation(), createTitle(), initializeChart(), makeFrameControlButtons(), makeSimulationButtons(), and makeSpeedDisplay().
Referenced by CellSocietyView().
HBox CellSocietyView.createErrorLocation () private
Definition at line 361 of file CellSocietyView.java.
Referenced by configureUI().
HBox CellSocietyView.createTitle () private
Returns
Definition at line 310 of file CellSocietyView.java.
References generateTitle(), and myTitleBox.
Referenced by configureUI().
void CellSocietyView.disableInitialButtons () private
Definition at line 271 of file CellSocietyView.java.
Referenced by CellSocietyView().
void CellSocietyView.displayFrameRate (int frameRate)
Definition at line 160 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML(), and CellSociety.reframeTimeline().
File CellSocietyView.displayXMLChooser ()
Definition at line 165 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML().
void CellSocietyView.generateChartLines (String[] cellNames)
Definition at line 207 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML().
void CellSocietyView.generateGrid () throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException private
Exceptions
ParserConfigurationException
SAXException
IOException
InvocationTargetException
IllegalArgumentException
IllegalAccessException
InstantiationException
SecurityException
NoSuchMethodException
ClassNotFoundException
Definition at line 291 of file CellSocietyView.java.
Referenced by CellSocietyView().
void CellSocietyView.generateTitle (String s)
Definition at line 150 of file CellSocietyView.java.
Referenced by createTitle().
Button CellSocietyView.getPauseElement ()
Definition at line 89 of file CellSocietyView.java.
References myPauseButton.
Referenced by CellSociety.configureListeners().
Button CellSocietyView.getPlayElement ()
Definition at line 85 of file CellSocietyView.java.
References myPlayButton.
Referenced by CellSociety.configureListeners().
Button CellSocietyView.getSlowdownElement ()
Definition at line 105 of file CellSocietyView.java.
References mySlowdownButton.
Referenced by CellSociety.configureListeners().
Button CellSocietyView.getSpeedupElement ()
Definition at line 101 of file CellSocietyView.java.
References mySpeedupButton.
Referenced by CellSociety.configureListeners().
Button CellSocietyView.getStepElement ()
Definition at line 93 of file CellSocietyView.java.
References myStepButton.
Referenced by CellSociety.configureListeners().
Button CellSocietyView.getXMLElement ()
Definition at line 97 of file CellSocietyView.java.
References myXMLButton.
Referenced by CellSociety.configureListeners().
void CellSocietyView.initializeButtons () private
Definition at line 259 of file CellSocietyView.java.
Referenced by CellSocietyView().
XYChart<Number, Number> CellSocietyView.initializeChart () private
Definition at line 221 of file CellSocietyView.java.
References myChart.
Referenced by configureUI().
HBox CellSocietyView.makeFrameControlButtons () private
Definition at line 332 of file CellSocietyView.java.
Referenced by configureUI().
HBox CellSocietyView.makeSimulationButtons () private
Parameters
topRow
Definition at line 321 of file CellSocietyView.java.
Referenced by configureUI().
HBox CellSocietyView.makeSpeedDisplay () private
Parameters
speedLabel
speedText
middleRow
Definition at line 346 of file CellSocietyView.java.
Referenced by configureUI().
void CellSocietyView.openDialogBox (String s)
Definition at line 109 of file CellSocietyView.java.
void CellSocietyView.setBlankGrid ()
Definition at line 142 of file CellSocietyView.java.
Referenced by CellSocietyView().
void CellSocietyView.setButtonsPause (boolean disable)
Definition at line 174 of file CellSocietyView.java.
Referenced by CellSociety.pauseAnimation(), and CellSociety.resumeAnimation().
void CellSocietyView.setErrorText ()
Definition at line 125 of file CellSocietyView.java.
void CellSocietyView.setGridGap (int gridLineGap)
Definition at line 302 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML().
void CellSocietyView.setupGameScene () private
Definition at line 252 of file CellSocietyView.java.
Referenced by CellSocietyView().
void CellSocietyView.updateChartLines (Cell cells[][], int numFrames, String[] names)
Definition at line 183 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML(), and CellSociety.updateGrid().
void CellSocietyView.updateSimGrid (Cell cellGrid[][])
Definition at line 117 of file CellSocietyView.java.
References Cell.getShape().
Referenced by CellSociety.readNewXML(), and CellSociety.updateGrid().
Member Data Documentation
final String CellSocietyView.DEFAULT_RESOURCE_PACKAGE = "" static
Definition at line 62 of file CellSocietyView.java.
final Font CellSocietyView.ERROR_FONT = Font.font("Arial", FontWeight.NORMAL, 12) static private
Definition at line 58 of file CellSocietyView.java.
final int CellSocietyView.GRID_SIZE = 400 static
Definition at line 63 of file CellSocietyView.java.
Referenced by CellSociety.readNewXML().
LineChart<Number, Number> CellSocietyView.myChart private
Definition at line 54 of file CellSocietyView.java.
Referenced by initializeChart().
Text CellSocietyView.myErrorMsg private
Definition at line 49 of file CellSocietyView.java.
Button CellSocietyView.myPauseButton private
Definition at line 43 of file CellSocietyView.java.
Referenced by getPauseElement().
Button CellSocietyView.myPlayButton private
Definition at line 42 of file CellSocietyView.java.
Referenced by getPlayElement().
ResourceBundle CellSocietyView.myResources private
Definition at line 53 of file CellSocietyView.java.
GridPane CellSocietyView.myRoot private
Definition at line 51 of file CellSocietyView.java.
Scene CellSocietyView.myScene private
Definition at line 41 of file CellSocietyView.java.
List<Series<Number, Number> > CellSocietyView.mySeries private
Definition at line 55 of file CellSocietyView.java.
GridPane CellSocietyView.mySimGrid private
Definition at line 52 of file CellSocietyView.java.
Button CellSocietyView.mySlowdownButton private
Definition at line 47 of file CellSocietyView.java.
Referenced by getSlowdownElement().
TextField CellSocietyView.mySpeedTextField private
Definition at line 48 of file CellSocietyView.java.
Button CellSocietyView.mySpeedupButton private
Definition at line 46 of file CellSocietyView.java.
Referenced by getSpeedupElement().
Stage CellSocietyView.myStage private
Definition at line 40 of file CellSocietyView.java.
Button CellSocietyView.myStepButton private
Definition at line 44 of file CellSocietyView.java.
Referenced by getStepElement().
HBox CellSocietyView.myTitleBox private
Definition at line 50 of file CellSocietyView.java.
Referenced by createTitle().
Button CellSocietyView.myXMLButton private
Definition at line 45 of file CellSocietyView.java.
Referenced by getXMLElement().
final Font CellSocietyView.TITLE_FONT = Font.font("Helvetica", FontWeight.NORMAL, 32) static private
Definition at line 59 of file CellSocietyView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/CellSocietyView.java