cellsociety_team13: SharkCell Class Reference
SharkCell Class Reference
Public Member Functions
SharkCell (String name)
SharkCell (Map< String, String > params)
Cell reproducingResult ()
int getEnergy ()
Cell ageOneChronon ()
boolean isDead ()
String toString ()
void replenishEnergy ()
Public Member Functions inherited from Cell
Cell (String name)
Cell (Map< String, String > params)
Shape getShape ()
Color getColor ()
String toString ()
void setColor (Color color)
Private Attributes
int myCurrAge
int myCurrEnergy
Static Private Attributes
static int myMaxEnergy
static int myReproducingAge
static Color myColor
Additional Inherited Members
Static Public Member Functions inherited from Cell
static void setCellSize (double width, double height)
Protected Member Functions inherited from Cell
double getWidth ()
double getHeight ()
Detailed Description
Definition at line 12 of file SharkCell.java.
Constructor & Destructor Documentation
SharkCell.SharkCell (String name)
Definition at line 21 of file SharkCell.java.
References Cell.getShape(), and myMaxEnergy.
Referenced by reproducingResult().
SharkCell.SharkCell (Map< String, String > params)
Definition at line 29 of file SharkCell.java.
References Cell.getShape(), and myMaxEnergy.
Member Function Documentation
Cell SharkCell.ageOneChronon ()
Implements ReproducingCell.
Definition at line 66 of file SharkCell.java.
int SharkCell.getEnergy ()
Definition at line 62 of file SharkCell.java.
References myCurrEnergy.
boolean SharkCell.isDead ()
Definition at line 72 of file SharkCell.java.
void SharkCell.replenishEnergy ()
Definition at line 80 of file SharkCell.java.
References myMaxEnergy.
Cell SharkCell.reproducingResult ()
Implements ReproducingCell.
Definition at line 52 of file SharkCell.java.
References Cell.Cell(), Strings.EMPTY_CELL, Strings.SHARK_CELL, and SharkCell().
String SharkCell.toString ()
Definition at line 76 of file SharkCell.java.
Member Data Documentation
Color SharkCell.myColor static private
Definition at line 19 of file SharkCell.java.
int SharkCell.myCurrAge private
Definition at line 16 of file SharkCell.java.
int SharkCell.myCurrEnergy private
Definition at line 17 of file SharkCell.java.
Referenced by getEnergy().
int SharkCell.myMaxEnergy static private
Definition at line 14 of file SharkCell.java.
Referenced by replenishEnergy(), and SharkCell().
int SharkCell.myReproducingAge static private
Definition at line 15 of file SharkCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/SharkCell.java