cellsociety_team13: TriangleGrid Class Reference
TriangleGrid Class Reference
Public Member Functions
TriangleGrid (double gridSize, Cell[][] cells)
void update (Cell[][] cells)
Group getGroup ()
Public Member Functions inherited from Grid
abstract void update (Cell[][] cells)
Private Member Functions
void setBack (Shape s, Cell c)
void setRed (Shape s)
Shape generateTriangle (int i, int j)
Private Attributes
Group myGrid
Shape[][] myShapes
double myHSpacing
double myVSpacing
Detailed Description
Definition at line 6 of file TriangleGrid.java.
Constructor & Destructor Documentation
TriangleGrid.TriangleGrid (double gridSize, Cell cells[][])
Definition at line 13 of file TriangleGrid.java.
References update().
Member Function Documentation
Shape TriangleGrid.generateTriangle (int i, int j) private
Definition at line 54 of file TriangleGrid.java.
References myHSpacing, and myVSpacing.
Referenced by update().
Group TriangleGrid.getGroup ()
Definition at line 41 of file TriangleGrid.java.
References myGrid.
void TriangleGrid.setBack (Shape s, Cell c) private
Definition at line 45 of file TriangleGrid.java.
References Cell.getColor().
Referenced by update().
void TriangleGrid.setRed (Shape s) private
Definition at line 50 of file TriangleGrid.java.
Referenced by update().
void TriangleGrid.update (Cell cells[][])
Definition at line 25 of file TriangleGrid.java.
References generateTriangle(), setBack(), and setRed().
Referenced by TriangleGrid().
Member Data Documentation
Group TriangleGrid.myGrid private
Definition at line 8 of file TriangleGrid.java.
Referenced by getGroup().
double TriangleGrid.myHSpacing private
Definition at line 10 of file TriangleGrid.java.
Referenced by generateTriangle().
Shape [][] TriangleGrid.myShapes private
Definition at line 9 of file TriangleGrid.java.
double TriangleGrid.myVSpacing private
Definition at line 11 of file TriangleGrid.java.
Referenced by generateTriangle().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/TriangleGrid.java