cellsociety_team13: CellSociety Class Reference
CellSociety Class Reference
Public Member Functions
CellSociety (Stage s) throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException
Cell createCellInstance (Map< String, String > cellParams) throws InstantiationException, IllegalAccessException, IllegalArgumentException, NoSuchMethodException, SecurityException, InvocationTargetException
Cell[][] createCellArray () throws InstantiationException, IllegalAccessException, IllegalArgumentException, ClassNotFoundException, NoSuchMethodException, SecurityException, InvocationTargetException
Private Member Functions
void setupAnimation ()
void retrieveParserInfo () throws NoSuchMethodException, InstantiationException, IllegalAccessException, InvocationTargetException
void configureListeners () throws IOException
KeyFrame start (int frameRate)
void increaseFrameRate ()
void decreaseFrameRate ()
void reframeTimeline ()
void updateGrid ()
void resumeAnimation ()
void pauseAnimation ()
void readNewXML ()
int[] stringToIntArray (String string)
Private Attributes
CellSocietyView myView
XMLParser myParser
int myFrameRate
SimController myController
Timeline myTimeline
Cell[][] myCells
int myNumFrames = 0
int count = 0
Detailed Description
Definition at line 21 of file CellSociety.java.
Constructor & Destructor Documentation
CellSociety.CellSociety (Stage s) throws ParserConfigurationException, SAXException, IOException, InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, ClassNotFoundException, NoSuchMethodException, SecurityException
Definition at line 34 of file CellSociety.java.
References configureListeners().
Member Function Documentation
void CellSociety.configureListeners () throws IOException private
Definition at line 148 of file CellSociety.java.
References decreaseFrameRate(), CellSocietyView.getPauseElement(), CellSocietyView.getPlayElement(), CellSocietyView.getSlowdownElement(), CellSocietyView.getSpeedupElement(), CellSocietyView.getStepElement(), CellSocietyView.getXMLElement(), increaseFrameRate(), pauseAnimation(), readNewXML(), resumeAnimation(), and updateGrid().
Referenced by CellSociety().
Cell [][] CellSociety.createCellArray () throws InstantiationException, IllegalAccessException, IllegalArgumentException, ClassNotFoundException, NoSuchMethodException, SecurityException, InvocationTargetException
Definition at line 66 of file CellSociety.java.
References createCellInstance(), XMLParser.getCellParamList(), XMLParser.getInitParamMap(), myCells, and stringToIntArray().
Referenced by readNewXML().
Cell CellSociety.createCellInstance (Map< String, String > cellParams) throws InstantiationException, IllegalAccessException, IllegalArgumentException, NoSuchMethodException, SecurityException, InvocationTargetException
Definition at line 45 of file CellSociety.java.
Referenced by createCellArray().
void CellSociety.decreaseFrameRate () private
Definition at line 168 of file CellSociety.java.
References reframeTimeline().
Referenced by configureListeners().
void CellSociety.increaseFrameRate () private
Definition at line 163 of file CellSociety.java.
References reframeTimeline().
Referenced by configureListeners().
void CellSociety.pauseAnimation () private
Definition at line 212 of file CellSociety.java.
References CellSocietyView.setButtonsPause().
Referenced by configureListeners(), and readNewXML().
void CellSociety.readNewXML () private
Definition at line 217 of file CellSociety.java.
References createCellArray(), CellSocietyView.displayFrameRate(), CellSocietyView.displayXMLChooser(), CellSocietyView.generateChartLines(), XMLParser.getCellParamList(), XMLParser.getInitParamMap(), CellSocietyView.GRID_SIZE, CellSocietyView.openDialogBox(), XMLParser.parseXMLFile(), pauseAnimation(), retrieveParserInfo(), Cell.setCellSize(), CellSocietyView.setGridGap(), setupAnimation(), CellSocietyView.updateChartLines(), and CellSocietyView.updateSimGrid().
Referenced by configureListeners().
void CellSociety.reframeTimeline () private
Definition at line 175 of file CellSociety.java.
References CellSocietyView.displayFrameRate(), and start().
Referenced by decreaseFrameRate(), and increaseFrameRate().
void CellSociety.resumeAnimation () private
Definition at line 206 of file CellSociety.java.
References CellSocietyView.setButtonsPause().
Referenced by configureListeners().
void CellSociety.retrieveParserInfo () throws NoSuchMethodException, InstantiationException, IllegalAccessException, InvocationTargetException private
Exceptions
ClassNotFoundException
NoSuchMethodException
InstantiationException
IllegalAccessException
InvocationTargetException
Definition at line 126 of file CellSociety.java.
References XMLParser.getInitParamMap(), and XMLParser.getSimParamMap().
Referenced by readNewXML().
void CellSociety.setupAnimation () private
Definition at line 112 of file CellSociety.java.
References start().
Referenced by readNewXML().
KeyFrame CellSociety.start (int frameRate) private
Definition at line 158 of file CellSociety.java.
References updateGrid().
Referenced by reframeTimeline(), and setupAnimation().
int [] CellSociety.stringToIntArray (String string) private
Definition at line 285 of file CellSociety.java.
Referenced by createCellArray().
void CellSociety.updateGrid () private
Definition at line 181 of file CellSociety.java.
References XMLParser.getCellParamList(), SimController.runOneSim(), CellSocietyView.updateChartLines(), and CellSocietyView.updateSimGrid().
Referenced by configureListeners(), and start().
Member Data Documentation
int CellSociety.count = 0 private
Definition at line 32 of file CellSociety.java.
Cell [][] CellSociety.myCells private
Definition at line 28 of file CellSociety.java.
Referenced by createCellArray().
SimController CellSociety.myController private
Definition at line 26 of file CellSociety.java.
int CellSociety.myFrameRate private
Definition at line 25 of file CellSociety.java.
int CellSociety.myNumFrames = 0 private
Definition at line 29 of file CellSociety.java.
XMLParser CellSociety.myParser private
Definition at line 24 of file CellSociety.java.
Timeline CellSociety.myTimeline private
Definition at line 27 of file CellSociety.java.
CellSocietyView CellSociety.myView private
Definition at line 23 of file CellSociety.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/CellSociety.java