cellsociety_team13: Neighbor Class Reference
Neighbor Class Reference abstract
Public Member Functions
abstract List< Integer[]> getNeighbors (Cell[][] grid, int row, int col, int scalar)
List< Integer[]> getNeighbors (Cell[][] grid, int row, int col)
Detailed Description
Definition at line 4 of file Neighbor.java.
Member Function Documentation
abstract List<Integer[]> Neighbor.getNeighbors (Cell grid[][], int row, int col, int scalar) abstract
Referenced by getNeighbors(), WatorController.getNeighbors(), and SimpleController.runOneSim().
List<Integer[]> Neighbor.getNeighbors (Cell grid[][], int row, int col)
Definition at line 15 of file Neighbor.java.
References getNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/Neighbor.java