cellsociety_team13: XMLParser Class Reference
XMLParser Class Reference
Public Member Functions
void parseXMLFile (File xmlFile) throws ParserConfigurationException, SAXException, IOException
void parseInitialTags ()
Map< String, String > getSimParamMap ()
Map< String, String > getInitParamMap ()
List< HashMap< String, String > > getCellParamList ()
Private Member Functions
Map< String, String > makeParamMap (NodeList paramList)
List< HashMap< String, String > > makeCellParamList (NodeList paramList)
Private Attributes
NodeList myNodeList
Map< String, String > mySimParam = new HashMap<String, String>()
Map< String, String > myInitParam = new HashMap<String, String>()
List< HashMap< String, String > > myCellParamList = new ArrayList<HashMap<String, String>>()
Detailed Description
Definition at line 20 of file XMLParser.java.
Member Function Documentation
List<HashMap<String, String> > XMLParser.getCellParamList ()
Definition at line 115 of file XMLParser.java.
References myCellParamList.
Referenced by CellSociety.createCellArray(), CellSociety.readNewXML(), CellSociety.updateColors(), and CellSociety.updateGrid().
Map<String, String> XMLParser.getInitParamMap ()
Definition at line 111 of file XMLParser.java.
References myInitParam.
Referenced by CellSociety.createCellArray(), CellSociety.readNewXML(), and CellSociety.retrieveParserInfo().
Map<String, String> XMLParser.getSimParamMap ()
Definition at line 107 of file XMLParser.java.
References mySimParam.
Referenced by CellSociety.retrieveParserInfo().
List<HashMap<String, String> > XMLParser.makeCellParamList (NodeList paramList) private
Definition at line 74 of file XMLParser.java.
Referenced by parseInitialTags().
Map<String, String> XMLParser.makeParamMap (NodeList paramList) private
Definition at line 60 of file XMLParser.java.
Referenced by parseInitialTags().
void XMLParser.parseInitialTags ()
Definition at line 38 of file XMLParser.java.
References makeCellParamList(), and makeParamMap().
Referenced by parseXMLFile().
void XMLParser.parseXMLFile (File xmlFile) throws ParserConfigurationException, SAXException, IOException
Definition at line 26 of file XMLParser.java.
References parseInitialTags().
Referenced by CellSociety.readNewXML().
Member Data Documentation
List<HashMap<String, String> > XMLParser.myCellParamList = new ArrayList<HashMap<String, String>>() private
Definition at line 24 of file XMLParser.java.
Referenced by getCellParamList().
Map<String, String> XMLParser.myInitParam = new HashMap<String, String>() private
Definition at line 23 of file XMLParser.java.
Referenced by getInitParamMap().
NodeList XMLParser.myNodeList private
Definition at line 21 of file XMLParser.java.
Map<String, String> XMLParser.mySimParam = new HashMap<String, String>() private
Definition at line 22 of file XMLParser.java.
Referenced by getSimParamMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/XMLParser.java