cellsociety_team13: ComplexController Class Reference
ComplexController Class Reference abstract
Public Member Functions
ComplexController (Map< String, String > parameters)
Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Public Member Functions inherited from Controller
abstract Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Member Functions
abstract void cellUpdate (Cell[][] grid, int row, int col, Cell[][] newGrid, List< Integer[]> updatedCoordinates) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
abstract List< String > typeTriage ()
Protected Member Functions inherited from Controller
boolean contains (List< Integer[]> updatedCoordinates, Integer[] curCoordinates)
Private Member Functions
Queue< Integer[]> coordinatesTriage (Cell[][] grid, List< String > strings)
Additional Inherited Members
Static Protected Member Functions inherited from Controller
static Cell makeCell (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Attributes inherited from Controller
Boundary myBoundary = new FiniteBoundary()
Neighbor myNeighbor = new FullNeighbor(myBoundary)
Detailed Description
Definition at line 8 of file ComplexController.java.
Constructor & Destructor Documentation
ComplexController.ComplexController (Map< String, String > parameters)
Definition at line 10 of file ComplexController.java.
Member Function Documentation
abstract void ComplexController.cellUpdate (Cell grid[][], int row, int col, Cell newGrid[][], List< Integer[]> updatedCoordinates) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException abstract protected
Referenced by runOneSim().
Queue<Integer[]> ComplexController.coordinatesTriage (Cell grid[][], List< String > strings) private
Definition at line 33 of file ComplexController.java.
Referenced by runOneSim().
Cell [][] ComplexController.runOneSim (Cell grid[][]) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Definition at line 13 of file ComplexController.java.
References cellUpdate(), Controller.contains(), coordinatesTriage(), and typeTriage().
abstract List<String> ComplexController.typeTriage () abstract protected
Referenced by runOneSim().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/ComplexController.java