cellsociety_team13: GridData Class Reference
GridData Class Reference
Public Member Functions
GridData (Cell[][] grid, int row, int col, Cell[][] newGrid, List< Integer[]> list)
Cell[][] getGrid ()
Cell curCell ()
Integer[] curCoord ()
int getRow ()
int getCol ()
Cell[][] getNewGrid ()
List< Integer[]> getList ()
void updateLocation (Cell cell)
Private Attributes
Cell[][] myGrid
int myRow
int myCol
Cell[][] myNewGrid
List< Integer[]> myList
Detailed Description
Definition at line 6 of file GridData.java.
Constructor & Destructor Documentation
GridData.GridData (Cell grid[][], int row, int col, Cell newGrid[][], List< Integer[]> list)
Definition at line 14 of file GridData.java.
Member Function Documentation
Cell GridData.curCell ()
Definition at line 27 of file GridData.java.
References myCol, and myRow.
Referenced by WatorController.manipulateCell().
Integer [] GridData.curCoord ()
Definition at line 36 of file GridData.java.
References myRow.
Referenced by WatorController.manipulateCell().
int GridData.getCol ()
Definition at line 45 of file GridData.java.
References myCol.
Referenced by AgentCell.cellSwap(), AgentCell.chooseNewLocation(), WatorController.getNeighbors(), WatorController.manipulateCell(), and AgentCell.sameLocation().
Cell [][] GridData.getGrid ()
Definition at line 23 of file GridData.java.
References myGrid.
Referenced by WatorController.getNeighbors(), AgentCell.leaveCurrentPatch(), and WatorController.manipulateCell().
List<Integer[]> GridData.getList ()
Definition at line 54 of file GridData.java.
References myList.
Referenced by WatorController.getNeighbors(), and WatorController.manipulateCell().
Cell [][] GridData.getNewGrid ()
Definition at line 49 of file GridData.java.
References myNewGrid.
Referenced by AgentCell.cellSwap(), AgentCell.leaveCurrentPatch(), and WatorController.manipulateCell().
int GridData.getRow ()
Definition at line 41 of file GridData.java.
References myRow.
Referenced by AgentCell.cellSwap(), AgentCell.chooseNewLocation(), WatorController.getNeighbors(), WatorController.manipulateCell(), and AgentCell.sameLocation().
void GridData.updateLocation (Cell cell)
Definition at line 58 of file GridData.java.
References myCol, and myRow.
Referenced by GroundCell.ageOneChronon().
Member Data Documentation
int GridData.myCol private
Definition at line 10 of file GridData.java.
Referenced by curCell(), getCol(), and updateLocation().
Cell [][] GridData.myGrid private
Definition at line 8 of file GridData.java.
Referenced by getGrid().
List<Integer[]> GridData.myList private
Definition at line 12 of file GridData.java.
Referenced by getList().
Cell [][] GridData.myNewGrid private
Definition at line 11 of file GridData.java.
Referenced by getNewGrid().
int GridData.myRow private
Definition at line 9 of file GridData.java.
Referenced by curCell(), curCoord(), getRow(), and updateLocation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/GridData.java