cellsociety_team13: GroundCell Class Reference
GroundCell Class Reference
Public Member Functions
void ageOneChronon (GridData data)
void update ()
int harvest ()
Public Member Functions inherited from Cell
Cell (String name)
Cell (Map< String, String > params)
Shape getShape ()
Color getColor ()
String toString ()
void setColor (Color color)
Private Attributes
int maxSugar
int curSugar
int curInterval
Static Private Attributes
static int sugarGrowBackRate
static int sugarGrowBackInterval
Additional Inherited Members
Static Public Member Functions inherited from Cell
static void setCellSize (double width, double height)
Protected Member Functions inherited from Cell
double getWidth ()
double getHeight ()
Detailed Description
Definition at line 4 of file GroundCell.java.
Member Function Documentation
void GroundCell.ageOneChronon (GridData data)
Implements Updatable.
Definition at line 16 of file GroundCell.java.
References update(), and GridData.updateLocation().
Referenced by AgentCell.cellSwap().
int GroundCell.harvest ()
Definition at line 30 of file GroundCell.java.
References curSugar.
Referenced by AgentCell.harvest().
void GroundCell.update ()
Definition at line 23 of file GroundCell.java.
Referenced by ageOneChronon(), and AgentCell.harvest().
Member Data Documentation
int GroundCell.curInterval private
Definition at line 10 of file GroundCell.java.
int GroundCell.curSugar private
Definition at line 9 of file GroundCell.java.
Referenced by harvest().
int GroundCell.maxSugar private
Definition at line 8 of file GroundCell.java.
int GroundCell.sugarGrowBackInterval static private
Definition at line 7 of file GroundCell.java.
int GroundCell.sugarGrowBackRate static private
Definition at line 6 of file GroundCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/GroundCell.java