cellsociety_team13: Controller Class Reference
Controller Class Reference abstract
Public Member Functions
abstract Cell[][] runOneSim (Cell[][] grid) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Controller (Map< String, String >parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Static Public Attributes
static final int X_COORD = 0
static final int Y_COORD = 1
Protected Member Functions
boolean contains (List< Integer[]> updatedCoordinates, Integer[] curCoordinates)
Static Protected Member Functions
static Cell makeCell (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Protected Attributes
Boundary myBoundary
Neighbor myNeighbor
Private Member Functions
void setBoundary (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
void setNeighbors (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Detailed Description
Definition at line 9 of file Controller.java.
Constructor & Destructor Documentation
Controller.Controller (Map< String, String > parameters) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException
Definition at line 19 of file Controller.java.
References setBoundary(), and setNeighbors().
Member Function Documentation
boolean Controller.contains (List< Integer[]> updatedCoordinates, Integer[] curCoordinates) protected
Definition at line 39 of file Controller.java.
Referenced by WatorController.getNeighbors(), SegregationController.newState(), and ComplexController.runOneSim().
static Cell Controller.makeCell (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException static protected
Definition at line 60 of file Controller.java.
Referenced by WatorController.cellUpdate(), FireController.newState(), LifeController.newState(), and SegregationController.newState().
abstract Cell [][] Controller.runOneSim (Cell grid[][]) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException abstract
Referenced by CellSociety.updateGrid().
void Controller.setBoundary (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException private
Definition at line 68 of file Controller.java.
Referenced by Controller().
void Controller.setNeighbors (String s) throws InstantiationException, IllegalAccessException, IllegalArgumentException, InvocationTargetException, NoSuchMethodException, SecurityException, ClassNotFoundException private
Definition at line 74 of file Controller.java.
Referenced by Controller().
Member Data Documentation
Boundary Controller.myBoundary protected
Definition at line 14 of file Controller.java.
Neighbor Controller.myNeighbor protected
Definition at line 15 of file Controller.java.
Referenced by WatorController.getNeighbors(), and SimpleController.runOneSim().
final int Controller.X_COORD = 0 static
Definition at line 11 of file Controller.java.
Referenced by AgentCell.chooseNewLocation(), AgentCell.closestEligibleNeighbor(), FireController.getNeighborsState(), LifeController.getNeighborsState(), SegregationController.getNeighborsState(), AgentCell.leaveCurrentPatch(), ComplexController.runOneSim(), and AgentCell.sameLocation().
final int Controller.Y_COORD = 1 static
Definition at line 12 of file Controller.java.
Referenced by AgentCell.chooseNewLocation(), AgentCell.closestEligibleNeighbor(), FireController.getNeighborsState(), LifeController.getNeighborsState(), SegregationController.getNeighborsState(), AgentCell.leaveCurrentPatch(), ComplexController.runOneSim(), and AgentCell.sameLocation().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team13/repository/src/Controller.java